name = "CBinding"
uuid = "d43a6710-96b8-4a2d-833c-c424785e5374"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "1.0.0"

[deps]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Clang_jll = "^9,^11"
Scratch = "^1"
julia = "^1.5"
